source 'https://rubygems.org'
gem 'ruby-lzma'
gem 'sqlite3'
gem 'json'
gem 'nokogiri'
gem 'pg'
gem 'sinatra'
#gem 'sinatra-cross_origin'
gem 'iami-logger', git: 'https://github.com/IamIpanda/RubyLogger.git'
gem 'thin'
